### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by nannano-sys** [nannano-sys/furima-31163#141]
https://furima-31163.herokuapp.com/
basic認証は
admin
2222

**Comment by tech-oa** [comment]
nannano-sys さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○出品者用及び購入者用のユーザーIDとパスワードがそれぞれ必要ですので、追記をお願いいたします。
○購入時のクレジットカード情報も執拗となりますので、追記をお願いいたします。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by nannano-sys** [comment]
アプリの不備ですか？
それとも情報が欲しいだけですか？

**Comment by nannano-sys** [comment]
ユーザー情報とクレジットカード情報を記載します
ユーザ１：sample1[email : sam1@sam.com pass : abc111]
ユーザ２ : sample2[email : sam2@sam.com pass : abc111]

カード情報
番号：4242424242424242
CVC：123

**Comment by tech-oa** [comment]
nannano-sys さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
購入者と出品者、どちらの情報なのかわかりかねるため、
以下のカリキュラムの指示に従い、お手数ですが再度ご提出をお願いします。
https://master.tech-camp.in/curriculums/5373

また、カード情報につきましても不足しておりますので、再度入力情報の確認をカリキュラムを参考にお願いいたします。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by nannano-sys** [comment]
出品者：sample1[email : sam1@sam.com pass : abc111]
購入者 : sample2[email : sam2@sam.com pass : abc111]
カード情報
番号：4242424242424242
CVC：123
期限：未来ならいつでも

**Comment by tech-oa** [comment]
nannano-sys さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移すること
→編集ページに遷移してしまいます。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by nannano-sys** [comment]
不備を修正しました。

**Comment by tech-oa** [comment]
nannano-sysさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by nannano-sys** [comment]
ありがとうございました。
